project:
  type: website

website:
  title: ""
  description: "Oxford, 16-18 July"
  navbar:
    logo: "/img/cgps.jpg"
    left:
      - href: index.qmd
        text: Home
      - text: Agenda
        menu:
          - "agenda Day1.qmd"
          - "agenda Day 2.qmd"
          - "agenda Day 3.qmd"
      - href: venue.qmd
        text: Venue
      - href: speakerinfo.qmd
        text: Speaker information
      - href: practicalinfo.qmd
        text: Practical information
      - href: FAQ.qmd
        text: FAQs
      - text: Training materials
        menu:
          - module1/module1.qmd
          - resources.qmd


  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 


format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]
    anchor-sections: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
