---
title: "Day 1, Tuesday, 16 July 2024"
---

**08:30 – 09:15** Registration

**09:15 – 09:30** Welcome & introduction

*Natacha Couto*

**SESSION 1: Definitions and real use-case scenarios of Digital Epidemiology in public health laboratories**

*Chair: Sophia David*

**09:30 – 10:00** Introduction to Digital Epidemiology

*David Aanensen*

**10:00 - 10:30** Applications of Digital Epidemiology in Public Health Scotland

*Matt Holden*

**10:30 – 11:00** Break

**11:00 – 11:30** Insights on the need for data integration for quick response in clinical practice

*Israa Mohammed*

**SESSION 2: Tools for data analysis, integraon and interpretaon**

*Chair: Natacha Couto*

**11:30 – 12:00** Application of Web-Based Tools for Digital Epidemiology

*Krisandra Allen*

**12:00 - 12:30** Tools for data analysis with hands-on exercise

*Monica Abrudan, Sophia David and Julio Diaz-Caballero*

**12:30 - 13:00** Tools for data integration with hands-on exercises (1)

*Emmanuelle Kumaran, Georgina Lewis-Woodhouse*

**13:00 - 14:00** Lunch

**14:00 - 14:30** Tools for data integration with hands-on exercises (2)

*Emmanuelle Kumaran , Georgina Lewis-Woodhouse*

**14:30 - 15:00** Tools for data visualisation and interpretation with hands-on exercise (1)

*Sophia David, Monica Abrudan, Julio Diaz-Caballero*

**15:00 -15:30** Break

**15:30 - 16:00** Tools for data visualisation and interpretation with hands-on exercise (2)

*Sophia David, Monica Abrudan, Julio Diaz-Caballero*

**SESSION 3: Examples of data sources facilitating rapid decisionmaking: clinical data, genomics, and social media**

*Chair: Julio Diaz-Caballero*

**16:00 - 16:30** Examples of data sources facilitating rapid decision-making: clinical data, genomics, and data from local governments

*Moritz Kraemer*

**16:30 - 17:00** The need for rapid data integration for quick response in clinical practice

*Charlene Rodrigues*

**17:00 - 17:30** Applications of Digital Epidemiology in Wyoming Public Health Lab

*Robert Petit III*

**18 :30** Dinner
